name: CI/CD Pipeline for Azure Databricks

on:
  workflow_dispatch:  # Manual triggering
  pull_request:
    branches:
      - main  # Trigger on PRs targeting main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Hardcoded Python version
      
      - name: Run Pytest
        run: |
                pip install -r requirements.txt
                echo "Listing directory structure:"
                ls -R src
                export PYTHONPATH=$PWD
                pytest src/tests --verbose
        working-directory: .

    

      # Log in to Azure using Service Principal
      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.CLIENTID }} \
            -p ${{ secrets.CLIENTSECRET }} \
            --tenant ${{ secrets.TENATID }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.CLIENTID }} # e.g., "12345678-1234-1234-1234-1234567890ab"
          AZURE_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}  # e.g., "abc~def1234567890"
          AZURE_TENANT_ID: ${{ secrets.TENATID }}  # e.g., "98765432-4321-4321-4321-0987654321ba"

      # Install Databricks CLI
      - name: Install Databricks CLI
        run: pip install databricks-cli

      # Configure Databricks CLI with token
      - name: Configure Databricks CLI
        run: |
          echo -e "[DEFAULT]\nhost = https://adb-1982449634857191.11.azuredatabricks.net\ntoken = dapi1d0380c74f4fda0d6d6ab84426294dc3-3" > ~/.databrickscfg
        # e.g., host = https://adb-1234567890123456.7.azuredatabricks.net
        # e.g., token = dapi1234567890abcdef1234567890abcdef

      # Extract branch name
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      # Update Databricks Git folder
      - name: Update Databricks Git folder
        run: |
         databricks repos update --repo-id "4180936112745165" --branch "${{ steps.extract_branch.outputs.branch }}"
        # e.g., /Repos/user@example.com/sample-databricks-project

      # Deploy notebooks to workspace
      
